/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/boardcast/': RouteRecordInfo<'/admin/boardcast/', '/admin/boardcast', Record<never, never>, Record<never, never>>,
    '/admin/boardcast/id': RouteRecordInfo<'/admin/boardcast/id', '/admin/boardcast/id', Record<never, never>, Record<never, never>>,
    '/admin/car/': RouteRecordInfo<'/admin/car/', '/admin/car', Record<never, never>, Record<never, never>>,
    '/admin/car/id': RouteRecordInfo<'/admin/car/id', '/admin/car/id', Record<never, never>, Record<never, never>>,
    '/admin/cartype': RouteRecordInfo<'/admin/cartype', '/admin/cartype', Record<never, never>, Record<never, never>>,
    '/admin/route': RouteRecordInfo<'/admin/route', '/admin/route', Record<never, never>, Record<never, never>>,
    '/admin/tracking': RouteRecordInfo<'/admin/tracking', '/admin/tracking', Record<never, never>, Record<never, never>>,
    '/auth/driver': RouteRecordInfo<'/auth/driver', '/auth/driver', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/lsp': RouteRecordInfo<'/auth/lsp', '/auth/lsp', Record<never, never>, Record<never, never>>,
    '/auth/otp': RouteRecordInfo<'/auth/otp', '/auth/otp', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/auth/shipper': RouteRecordInfo<'/auth/shipper', '/auth/shipper', Record<never, never>, Record<never, never>>,
    '/bill': RouteRecordInfo<'/bill', '/bill', Record<never, never>, Record<never, never>>,
    '/delivery': RouteRecordInfo<'/delivery', '/delivery', Record<never, never>, Record<never, never>>,
    '/invoice': RouteRecordInfo<'/invoice', '/invoice', Record<never, never>, Record<never, never>>,
    '/lspdriver/': RouteRecordInfo<'/lspdriver/', '/lspdriver', Record<never, never>, Record<never, never>>,
    '/lspdriver/chat': RouteRecordInfo<'/lspdriver/chat', '/lspdriver/chat', Record<never, never>, Record<never, never>>,
    '/lspdriver/id': RouteRecordInfo<'/lspdriver/id', '/lspdriver/id', Record<never, never>, Record<never, never>>,
    '/partner/': RouteRecordInfo<'/partner/', '/partner', Record<never, never>, Record<never, never>>,
    '/partner/booking/': RouteRecordInfo<'/partner/booking/', '/partner/booking', Record<never, never>, Record<never, never>>,
    '/partner/booking/id': RouteRecordInfo<'/partner/booking/id', '/partner/booking/id', Record<never, never>, Record<never, never>>,
    '/partner/car': RouteRecordInfo<'/partner/car', '/partner/car', Record<never, never>, Record<never, never>>,
    '/partner/chat': RouteRecordInfo<'/partner/chat', '/partner/chat', Record<never, never>, Record<never, never>>,
    '/partner/driver': RouteRecordInfo<'/partner/driver', '/partner/driver', Record<never, never>, Record<never, never>>,
    '/partner/findjob': RouteRecordInfo<'/partner/findjob', '/partner/findjob', Record<never, never>, Record<never, never>>,
    '/partner/myjob/': RouteRecordInfo<'/partner/myjob/', '/partner/myjob', Record<never, never>, Record<never, never>>,
    '/partner/myjob/id': RouteRecordInfo<'/partner/myjob/id', '/partner/myjob/id', Record<never, never>, Record<never, never>>,
    '/partner/pricerate': RouteRecordInfo<'/partner/pricerate', '/partner/pricerate', Record<never, never>, Record<never, never>>,
    '/partner/profile/': RouteRecordInfo<'/partner/profile/', '/partner/profile', Record<never, never>, Record<never, never>>,
    '/partner/profile/setting': RouteRecordInfo<'/partner/profile/setting', '/partner/profile/setting', Record<never, never>, Record<never, never>>,
    '/partner/route': RouteRecordInfo<'/partner/route', '/partner/route', Record<never, never>, Record<never, never>>,
    '/partner/tracking/': RouteRecordInfo<'/partner/tracking/', '/partner/tracking', Record<never, never>, Record<never, never>>,
    '/partner/tracking/id': RouteRecordInfo<'/partner/tracking/id', '/partner/tracking/id', Record<never, never>, Record<never, never>>,
    '/producttrack': RouteRecordInfo<'/producttrack', '/producttrack', Record<never, never>, Record<never, never>>,
    '/test1': RouteRecordInfo<'/test1', '/test1', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
    '/user/booking/': RouteRecordInfo<'/user/booking/', '/user/booking', Record<never, never>, Record<never, never>>,
    '/user/booking/cartype': RouteRecordInfo<'/user/booking/cartype', '/user/booking/cartype', Record<never, never>, Record<never, never>>,
    '/user/booking/ftl': RouteRecordInfo<'/user/booking/ftl', '/user/booking/ftl', Record<never, never>, Record<never, never>>,
    '/user/booking/ltl': RouteRecordInfo<'/user/booking/ltl', '/user/booking/ltl', Record<never, never>, Record<never, never>>,
    '/user/booking/matching': RouteRecordInfo<'/user/booking/matching', '/user/booking/matching', Record<never, never>, Record<never, never>>,
    '/user/booking/route': RouteRecordInfo<'/user/booking/route', '/user/booking/route', Record<never, never>, Record<never, never>>,
    '/user/checkcar': RouteRecordInfo<'/user/checkcar', '/user/checkcar', Record<never, never>, Record<never, never>>,
    '/user/complaint': RouteRecordInfo<'/user/complaint', '/user/complaint', Record<never, never>, Record<never, never>>,
    '/user/contact': RouteRecordInfo<'/user/contact', '/user/contact', Record<never, never>, Record<never, never>>,
    '/user/history/': RouteRecordInfo<'/user/history/', '/user/history', Record<never, never>, Record<never, never>>,
    '/user/history/id': RouteRecordInfo<'/user/history/id', '/user/history/id', Record<never, never>, Record<never, never>>,
    '/user/job': RouteRecordInfo<'/user/job', '/user/job', Record<never, never>, Record<never, never>>,
    '/user/payment/': RouteRecordInfo<'/user/payment/', '/user/payment', Record<never, never>, Record<never, never>>,
    '/user/payment/id': RouteRecordInfo<'/user/payment/id', '/user/payment/id', Record<never, never>, Record<never, never>>,
    '/user/profile/': RouteRecordInfo<'/user/profile/', '/user/profile', Record<never, never>, Record<never, never>>,
    '/user/profile/address': RouteRecordInfo<'/user/profile/address', '/user/profile/address', Record<never, never>, Record<never, never>>,
    '/user/profile/setting': RouteRecordInfo<'/user/profile/setting', '/user/profile/setting', Record<never, never>, Record<never, never>>,
    '/user/tracking/': RouteRecordInfo<'/user/tracking/', '/user/tracking', Record<never, never>, Record<never, never>>,
    '/user/tracking/id': RouteRecordInfo<'/user/tracking/id', '/user/tracking/id', Record<never, never>, Record<never, never>>,
  }
}
